# See https://github.com/liamg/peridot for help configuring peridot
debug: false
modules:
  - name: packages
    source: ./packages
  - name: git templates
    source: ./git-templates
  - name: git
    source: builtin:git
    variables:
      email: liamgalvin@protonmail.com
      username: Liam Galvin
      editor: nvim
      aliases:
        - uc = reset --soft HEAD~1
      ignores:
        - .idea
        - .vscode
      extra: |
        [init]
        	templatedir = ~/.git-templates
        [url "git@github.com:"]
          insteadOf = https://github.com/
        [url "ssh://git@bitbucket.org/"]
          insteadOf = https://bitbucket.org
  - name: fonts
    source: ./fonts
  - name: zsh
    source: ./zsh
  - name: alacritty
    source: ./alacritty
  - name: neovim
    source: ./neovim
  - name: gtk
    source: ./gtk
  - name: i3
    source: ./i3
  - name: sway
    source: ./sway
  - name: polybar
    source: ./polybar
  - name: manual installs
    depends_on:
      - zsh
      - packages
    source: ./manual-installs

