files:
- target: "{{ .user_home_dir }}/.zshrc"
  source: ./zshrc
- target: "{{ .user_home_dir }}/.zshaliases"
  source: ./aliases
- target: "{{ .user_home_dir }}/.zprofile"
  source: ./zprofile
- target: "{{ .user_home_dir }}/.zshenv"
  source: ./zshenv
- target: "{{ .user_config_dir }}/bearings/config.yml"
  source: ./bearings.yml
