
start_sway() {
	export MOZ_ENABLE_WAYLAND=1
    flags=""
    # if nvidia drivers are in use, apologise to sway via flags
    pacman -Qi nvidia >/dev/null && flags="--my-next-gpu-wont-be-nvidia"
    which sway >/dev/null && exec sway $flags
}


echo
echo "1. X"
echo "2. Sway"
echo "3. Hyprland"
echo "4. Shell"
echo

read REPLY\?"Enter your choice: "
echo

[[ "$REPLY" == "1" ]] && startx
[[ "$REPLY" == "2" ]] && start_sway
[[ "$REPLY" == "3" ]] && Hyprland

