
start_wayland() {
	export MOZ_ENABLE_WAYLAND=1
    flags=""
    # if nvidia drivers are in use, apologise to sway via flags
    pacman -Qi nvidia >/dev/null && flags="--my-next-gpu-wont-be-nvidia"
    which sway >/dev/null && exec sway $flags
}

# launch sway if we're logging in to the machine and it's installed
if [[ -z $DISPLAY && $TTY = /dev/tty1 ]]; then
    which startx 2>&1 >/dev/null && startx || start_wayland
fi

