# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall

zstyle :compinstall filename '{{ .user_home_dir }}/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
	aws
	docker
	git
	golang
	terraform
	z
)


source_if_exists () {
    [[ -f "$1" ]] && source $1 || true
}

export NVM_DIR="$HOME/.nvm"
source_if_exists "$NVM_DIR/nvm.sh"  # This loads nvm
source_if_exists "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

source_if_exists "$HOME/.zshaliases"

#bearings-auto:start
function configure_bearings() {
    PROMPT="$(bearings prompt -s zsh -e $?)"
}
[ ! "$TERM" = "linux" ] && precmd_functions+=(configure_bearings)
#bearings-auto:end

