files:
  - target: "{{ .user_config_dir }}/nvim/init.lua"
    source: ./init.lua
    disable_templating: true
  - target: "{{ .user_config_dir }}/nvim/lua/plugins.lua"
    source: ./plugins.lua
    disable_templating: true
  - target: "{{ .user_config_dir }}/nvim/lua/config/treesitter.lua"
    source: ./config/treesitter.lua
    disable_templating: true
  - target: "{{ .user_config_dir }}/nvim/lua/config/go.lua"
    source: ./config/go.lua
    disable_templating: true
  - target: "{{ .user_config_dir }}/nvim/lua/config/gui.lua"
    source: ./config/gui.lua
    disable_templating: true
  - target: "{{ .user_config_dir }}/nvim/lua/config/tree.lua"
    source: ./config/tree.lua
    disable_templating: true
  - target: "{{ .user_config_dir }}/nvim/lua/config/floats.lua"
    source: ./config/floats.lua
    disable_templating: true
  - target: "{{ .user_config_dir }}/nvim/lua/config/completion.lua"
    source: ./config/completion.lua
    disable_templating: true
  - target: "{{ .user_config_dir }}/nvim/lua/config/org.lua"
    source: ./config/org.lua
    disable_templating: true
scripts:
  after_file_change:
    interactive: true
    command:  "nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync' && echo GoInstallBinaries | nvim --headless -Es && echo 'TSInstall go' | nvim --headless -Es"
