modules:
  - name: apt
    source: builtin:apt
    filters:
      distro:
        - ubuntu
    variables:
      packages:
        - bat
        - build-essential
        - ca-certificates
        - cmake
        - curl
        - dnsutils
        - dunst
        - fd-find
        - flameshot
        - git
        - gnupg
        - htop
        - i3wm
        - i3lock
        - jq
        - libasound2-dev
        - libssl-dev
        - libdbus-1-dev
        - libncurses-dev
        - libssl-dev
        - libpulse-dev
        - libncursesw5-dev
        - libdbus-1-dev
        - libpulse-dev
        - libssl-dev
        - libxcb1-dev
        - libxcb-render0-dev
        - libxcb-shape0-dev
        - libxcb-xfixes0-dev
        - lsb-release
        - neovim
        - pkg-config
        - playerctl
        - python3-dev
        - python3-pip
        - regolith-look-midnight
        - ripgrep
        - tree
        - unzip
        - wget
        - xclip
        - libgtk-3-dev
        - libpango1.0-dev
        - libgdk-pixbuf2.0-dev
        - libcairo2-dev
        - libglib2.0-dev
        - libgcc-8-dev
        - glibc-source 
  - name: pacman
    source: builtin:pacman
    filters:
      distro:
      - arch
    variables:
      packages:
        - alacritty
        - alsa-utils 
        - autoconf
        - automake
        - base
        - bat
        - bbswitch
        - bison
        - code
        - dhclient
        - dhcpcd
        - dmenu
        - dnsutils
        - docker
        - efibootmgr
        - fakeroot
        - fd
        - feh
        - firefox
        - flameshot
        - flex
        - gcc
        - git
        - gnu-netcat
        - grim
        - grub
        - gtk-layer-shell
        - htop
        - i3-gaps
        - i3lock
        - jq
        - linux
        - linux-firmware
        - m4
        - make
        - man-db
        - man-pages
        - mesa-utils
        - neovim
        - net-tools
        - networkmanager
        - ntp
        - openssh
        - patch
        - pkgconf
        - playerctl
        - pulseaudio
        - qmk
        - ripgrep
        - ruby
        - sl
        - slurp
        - sudo
        - sway
        - swaylock
        - texinfo
        - ttf-dejavu
        - ttf-droid
        - ttf-roboto
        - vi
        - vim
        - wayland
        - wget
        - which
        - xdg-utils
        - xdg-desktop-portal-wlr
        - xf86-video-nouveau
        - xorg-xwayland
        - yay
        - zoom
        - zsh
  - name: yay
    source: builtin:yay
    variables:
      packages:
        - noto-fonts-emoji
        - polybar
        - nerd-fonts-complete
        - hyprland-git

